name: Build And Release gopkg.microglot.org

on:
  push:
    branches:
      - "main"
  workflow_dispatch: {}

jobs:
  build_release:
    name: Build And Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - uses: actions/cache@v4
        id: tools
        with:
          path: |
            .bin
          key: ${{ runner.os }}-${{ hashFiles('internal/tools/go.sum') }}
      - name: Install build/test tools
        if: steps.tools.outputs.cache-hit != 'true'
        run: make tools
      - name: Generate build
        run: make build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: whoami
          postCommands: make release
